# Install.ps1 — Register `ydl` as a PowerShell function in the user's $PROFILE.
#
# Why: the ydl.bat shim works for simple cases, but PowerShell 5.1 mangles `&`
# in quoted args when launching external batch files (your URL's `&list=...`
# leaks to cmd.exe as separate commands). Registering `ydl` as a function keeps
# the call in-process, so URLs with `&` Just Work.
#
# Usage (one-time, from this folder):
#   .\Install.bat
#
# Then open a NEW PowerShell window. Test:
#   ydl --help
#   ydl "https://www.youtube.com/watch?v=VIDEO_ID&list=..."

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ps1 = Join-Path $scriptDir "_ydl.ps1"

if (-not (Test-Path $ps1)) {
    Write-Host "ERROR: _ydl.ps1 not found at $ps1" -ForegroundColor Red
    exit 1
}

# Marker so re-running this script replaces the previous block instead of stacking.
$markerStart = "# >>> ydl function (auto-generated by Install.ps1) >>>"
$markerEnd   = "# <<< ydl function <<<"

$block = @"
$markerStart
function ydl {
    & "$ps1" @args
}
$markerEnd
"@

# Make sure $PROFILE exists.
if (-not (Test-Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    Write-Host "Created profile: $PROFILE" -ForegroundColor Cyan
}

# Strip any previous block, then append the fresh one.
$current = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
if ($null -eq $current) { $current = "" }

$pattern = [regex]::Escape($markerStart) + "[\s\S]*?" + [regex]::Escape($markerEnd)
$cleaned = [regex]::Replace($current, $pattern, "").TrimEnd()

$new = if ($cleaned) { "$cleaned`r`n`r`n$block`r`n" } else { "$block`r`n" }
Set-Content -Path $PROFILE -Value $new -Encoding UTF8

Write-Host ""
Write-Host "OK. Registered `ydl` function in:" -ForegroundColor Green
Write-Host "  $PROFILE"
Write-Host ""
Write-Host "Open a NEW PowerShell window, then try:" -ForegroundColor Cyan
Write-Host "  ydl --help"
Write-Host '  ydl "https://www.youtube.com/watch?v=jNQXAC9IVRw"'
